server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/massdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
